
server.port=8090

logging.level.org.hibernate.SQL=DEBUG


security.jwt.expiration-ms=36000000
spring.servlet.multipart.max-file-size=10MB
security.jwt.base64-secret=/XfS7IqwUkpQ9Wc84AgJfGt5cbLpQijCO0scKeNxT0E=
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=studyreview31@gmail.com
spring.mail.password=zsaa vokr qeup nbvp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/smart_review?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=smart_review
spring.datasource.password=smart_review_pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate 6 on Boot 3.x)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
